# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
enable_free_tier: true

knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto

chat:
  auto_reply: true

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  assess_linked_issues: true

  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - WIP
      - DRAFT
      - "[SKIP]"
    base_branches:
      - main
      - develop

  path_filters:
    # ビルド成果物・依存関係
    - "!node_modules/**"
    - "!.wrangler/**"
    - "!dist/**"
    - "!build/**"
    - "!coverage/**"
    - "!*.min.js"
    - "!package-lock.json"
    - "!pnpm-lock.yaml"

    # Xcode関連
    - "!*.xcworkspace/**"
    - "!*.xcodeproj/project.xcworkspace/**"
    - "!*.xcodeproj/xcuserdata/**"
    - "!DerivedData/**"

    # ライセンス・変更履歴
    - "!LICENSE*"
    - "!CHANGELOG*"
    - "!AUTHORS*"
    - "!CONTRIBUTORS*"

    # 画像・メディア
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.ico"
    - "!**/*.pdf"

    # テストフィクスチャ・スナップショット
    - "!**/fixtures/**"
    - "!**/mocks/**"
    - "!**/__snapshots__/**"

  path_instructions:
    # ===========================================
    # TypeScript/Hono バックエンド
    # ===========================================
    - path: "backend/src/**/*.ts"
      instructions: |
        ## レビュー基準

        ### 1. 型安全性
        - **any型は絶対禁止** → unknown型を使用
        - 全関数で明示的なreturn型を宣言
        - const優先、letは再代入が必要な場合のみ

        ### 2. クリーンアップ（重要）
        - **未使用import**: 使われていないimport文を指摘し削除を要求
        - **未使用変数・関数**: 定義されているが参照されていないものを特定
        - **未使用type/interface**: 定義されているが使用されていない型を検出
        - **到達不可能コード**: return後のコード等を特定
        - **デッドコード**: コメントアウトされたコードは削除を要求

        ### 3. Honoパターン
        - 型付きコンテキスト: `new Hono<{ Bindings: Bindings }>()`
        - routes/にビジネスロジックを書かない（Service層へ分離）
        - レスポンス形式: `{ success: boolean, data?: T, error?: string }`

        ### 4. エラーハンドリング
        - try-catchで適切にエラーを捕捉
        - エラーメッセージは具体的に

    # ===========================================
    # TypeScript テスト
    # ===========================================
    - path: "backend/**/*.test.ts"
      instructions: |
        ## テストレビュー基準
        - Hono testClientの使用確認
        - 適切なモック設計
        - テストケースの網羅性
        - 未使用のテストヘルパー・モックを指摘

    # ===========================================
    # Swift/iOS アプリケーション
    # ===========================================
    - path: "ios/**/*.swift"
      instructions: |
        ## レビュー基準

        ### 1. 基本要件
        - 明示的型宣言: `var isLoading: Bool = false`
        - camelCase定数: `let maxRetryCount: Int = 3`
        - ファイル400行以下（超過時はコンポーネント分割を要求）

        ### 2. クリーンアップ（重要）
        - **未使用import**: 使われていないimport文を指摘し削除を要求
        - **未使用変数・関数・プロパティ**: 定義されているが参照されていないものを特定
        - **未使用protocol/struct/class**: 定義されているが使用されていない型を検出
        - **未使用extension**: プロジェクト内で使用されていないextensionメソッドを検出
        - **到達不可能コード**: return/throw後のコード等を特定
        - **デッドコード**: コメントアウトされたコードは削除を要求

        ### 3. SwiftUI
        - @StateObject: 作成・所有する場合
        - @ObservedObject: 親から受け取る場合
        - @State: ローカルUI状態のみ
        - View body 50行以下（超過時はコンポーネント抽出）
        - NavigationStack使用（NavigationView非推奨）

        ### 4. 非同期・メモリ管理
        - async/await必須（completion handler禁止）
        - UI更新には@MainActor適用
        - クロージャでは[weak self]使用

        ### 5. HealthKit
        - `HKHealthStore.isHealthDataAvailable()`の事前確認
        - 全HealthKit操作でasync/await使用

    # ===========================================
    # 設定ファイル
    # ===========================================
    - path: "backend/package.json"
      instructions: |
        設定ファイルのベストプラクティス準拠を確認
        - 不要な依存関係がないか
        - 設定の一貫性
    - path: "backend/tsconfig.json"
      instructions: |
        設定ファイルのベストプラクティス準拠を確認
        - TypeScript設定の適切性
        - 設定の一貫性
    - path: "backend/wrangler.toml"
      instructions: |
        設定ファイルのベストプラクティス準拠を確認
        - Cloudflare Workers設定の適切性
        - 設定の一貫性

  # ===========================================
  # ツール設定
  # ===========================================
  tools:
    # TypeScript/JavaScript
    biome:
      enabled: true

    # Swift
    swiftlint:
      enabled: true

    # セキュリティ（APIキー漏洩検出）
    gitleaks:
      enabled: true

    # シェルスクリプト
    shellcheck:
      enabled: true

    # GitHub統合
    github-checks:
      enabled: true
      timeout_ms: 90000

    # AST解析（セキュリティルール）
    ast-grep:
      essential_rules: true

# ===========================================
# トーン設定
# ===========================================
tone_instructions: |
  - プロフェッショナルで建設的なレビューを行う
  - 問題発見時は具体的な改善案を提示
  - セキュリティ・品質問題は明確に指摘

  ## クリーンアップ重視
  - 未使用コード（import, 変数, 関数, 型）は必ず指摘し、削除を強く推奨
  - コメントアウトされたコードは削除を要求
  - デッドファイル（どこからも参照されていないファイル）を発見した場合は報告
