# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
enable_free_tier: true

knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto

chat:
  auto_reply: true

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  assess_linked_issues: true

  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - WIP
      - DRAFT
      - "[SKIP]"
    base_branches:
      - main
      - develop

  path_filters:
    # ビルド成果物・依存関係
    - "!node_modules/**"
    - "!.wrangler/**"
    - "!dist/**"
    - "!build/**"
    - "!coverage/**"
    - "!*.min.js"
    - "!package-lock.json"
    - "!pnpm-lock.yaml"

    # Xcode関連
    - "!*.xcworkspace/**"
    - "!*.xcodeproj/project.xcworkspace/**"
    - "!*.xcodeproj/xcuserdata/**"
    - "!DerivedData/**"

    # ドキュメント・レビューファイル除外
    - "!**/*.md"
    - "!**/*.txt"
    - "!**/*.rst"
    - "!**/*.adoc"
    - "!docs/**"
    - "!CHANGELOG*"
    - "!README*"
    - "!LICENSE*"
    - "!AUTHORS*"
    - "!CONTRIBUTORS*"

    # 画像・メディア
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.ico"
    - "!**/*.pdf"
    - "!**/*.webp"
    - "!**/*.bmp"
    - "!**/*.tiff"

    # データ・ログファイル（設定ファイルは含める）
    - "!**/*.log"
    - "!**/*.cache"
    - "!**/*.tmp"
    - "!**/*.temp"

    # テストフィクスチャ・スナップショット
    - "!**/fixtures/**"
    - "!**/mocks/**" 
    - "!**/__snapshots__/**"
    - "!**/test-data/**"

    # その他の不要ファイル
    - "!**/.DS_Store"
    - "!**/*.tmp"
    - "!**/*.temp"
    - "!**/*.cache"

  path_instructions:
    # ===========================================
    # TypeScript/Hono バックエンド
    # ===========================================
    - path: "backend/src/**/*.ts"
      instructions: |
        ## レビュー基準

        ### 1. 型安全性
        - **any型は絶対禁止** → unknown型を使用
        - 全関数で明示的なreturn型を宣言
        - const優先、letは再代入が必要な場合のみ

        ### 2. クリーンアップ（重要）
        - **未使用import**: 使われていないimport文を指摘し削除を要求
        - **未使用変数・関数**: 定義されているが参照されていないものを特定
        - **未使用type/interface**: 定義されているが使用されていない型を検出
        - **到達不可能コード**: return後のコード等を特定
        - **デッドコード**: コメントアウトされたコードは削除を要求

        ### 3. Honoパターン
        - 型付きコンテキスト: `new Hono<{ Bindings: Bindings }>()`
        - routes/にビジネスロジックを書かない（Service層へ分離）
        - レスポンス形式: `{ success: boolean, data?: T, error?: string }`

        ### 4. エラーハンドリング
        - try-catchで適切にエラーを捕捉
        - エラーメッセージは具体的に

    # ===========================================
    # TypeScript テスト
    # ===========================================
    - path: "backend/**/*.test.ts"
      instructions: |
        ## テストレビュー基準
        - **any型使用許可**: テストファイルでは実用性重視でany型の使用を許可
        - テストヘルパー・モックでのany型は問題なし（/* eslint-disable */コメント推奨）
        - Hono testClientの使用確認
        - 適切なモック設計
        - テストケースの網羅性
        - 未使用のテストヘルパー・モックを指摘

    # ===========================================
    # Swift/iOS アプリケーション
    # ===========================================
    - path: "ios/**/*.swift"
      instructions: |
        ## レビュー基準

        ### 1. 基本要件
        - 明示的型宣言: `var isLoading: Bool = false`
        - camelCase定数: `let maxRetryCount: Int = 3`
        - ファイル400行以下（超過時はコンポーネント分割を要求）

        ### 2. クリーンアップ（重要）
        - **未使用import**: 使われていないimport文を指摘し削除を要求
        - **未使用変数・関数・プロパティ**: 定義されているが参照されていないものを特定
        - **未使用protocol/struct/class**: 定義されているが使用されていない型を検出
        - **未使用extension**: プロジェクト内で使用されていないextensionメソッドを検出
        - **到達不可能コード**: return/throw後のコード等を特定
        - **デッドコード**: コメントアウトされたコードは削除を要求

        ### 3. SwiftUI
        - @StateObject: 作成・所有する場合
        - @ObservedObject: 親から受け取る場合
        - @State: ローカルUI状態のみ
        - View body 120行以下（超過時はコンポーネント抽出）
        - NavigationStack使用（NavigationView非推奨）

        ### 4. 非同期・メモリ管理
        - async/await必須（completion handler禁止）
        - UI更新には@MainActor適用
        - クロージャでは[weak self]使用

        ### 5. HealthKit
        - `HKHealthStore.isHealthDataAvailable()`の事前確認
        - 全HealthKit操作でasync/await使用

        ### 6. ファイル構成
        - **単一責任**: 1ファイルに複数のManagerクラスが含まれている場合は分離を要求
        - **DEBUGコード分離**: #if DEBUGブロックが3箇所以上ある場合、別ファイル（+Preview.swift）への抽出を推奨
        - **コンポーネント再利用**: 類似UIパターン（トースト、カード等）が複数ファイルにある場合、共通コンポーネント化を推奨
        - **ネストしたコンポーネント**: 1ファイル内にprivate structが4つ以上ある場合、別ファイルへの抽出を検討

        ### 7. エラーハンドリング
        - **サイレントフェイル禁止**: catch内でprint()のみは警告。ユーザー通知またはエラー状態の更新を要求
        - **DEBUGフォールバック警告**: #if DEBUG内でモックデータを返す場合、本番時の動作が明確か確認
        - **エラー情報保持**: エラーをラップする際に元の情報が失われていないか確認
        - **エラーメッセージ**: LocalizedError準拠でユーザーフレンドリーなメッセージを提供

    # ===========================================
    # 設定ファイル
    # ===========================================
    - path: "backend/package.json"
      instructions: |
        設定ファイルのベストプラクティス準拠を確認
        - 不要な依存関係がないか
        - 設定の一貫性
    - path: "backend/tsconfig.json"
      instructions: |
        設定ファイルのベストプラクティス準拠を確認
        - TypeScript設定の適切性
        - 設定の一貫性
    - path: "backend/wrangler.toml"
      instructions: |
        設定ファイルのベストプラクティス準拠を確認
        - Cloudflare Workers設定の適切性
        - 設定の一貫性

  # ===========================================
  # ツール設定
  # ===========================================
  tools:
    # TypeScript/JavaScript
    biome:
      enabled: true

    # Swift
    swiftlint:
      enabled: true

    # セキュリティ（APIキー漏洩検出）
    gitleaks:
      enabled: true

    # シェルスクリプト
    shellcheck:
      enabled: true

    # GitHub統合
    github-checks:
      enabled: true
      timeout_ms: 90000

    # AST解析（セキュリティルール）
    ast-grep:
      essential_rules: true

# ===========================================
# トーン設定
# ===========================================
tone_instructions: "Professional constructive review. Check unused code, security issues, file size (400-line limit), and silent error handling patterns."
