# =============================================================================
# Tempo AI - SwiftLint Configuration
# =============================================================================
#
# 配置場所: プロジェクトルート/.swiftlint.yml
#
# 参考: https://github.com/realm/SwiftLint
# =============================================================================

# 除外するディレクトリ・ファイル
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - "*/Generated/*"
  - "**/Package.swift"
  - backend
  - docs

# iOS プロジェクトのパスを明示的に指定
included:
  - ios

# 有効にするルール（デフォルト + 追加）
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

# 無効にするルール
disabled_rules:
  - trailing_whitespace # Xcodeが自動挿入することがあるため
  - todo # TODOコメントを許可
  - opening_brace # SwiftUIとの相性

# ルールのカスタマイズ
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 10

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - ID
    - UI
    - VM

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - to
    - at
    - by
    - ok
    - vm

# Nesting（ネストの深さ）
nesting:
  type_level: 3
  function_level: 5

# コロン周りのスペース
colon:
  apply_to_dictionaries: true

# カンマ周りのスペース
comma: warning

# 垂直方向の空白行
vertical_whitespace:
  max_empty_lines: 2

# Modifier の順序
modifier_order:
  preferred_modifier_order:
    - override
    - acl
    - setterACL
    - dynamic
    - mutating
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

# Force Unwrapping（強制アンラップ）を警告に
force_unwrapping:
  severity: warning

# Force Cast を警告に（エラーではなく）
force_cast: warning

# Force Try を警告に
force_try: warning

# カスタムルール（プロジェクト固有）
custom_rules:
  # print文の使用を警告
  no_print_statement:
    name: "No Print Statement"
    regex: "\\bprint\\s*\\("
    message: "本番コードでは print() の代わりに Logger を使用してください"
    severity: warning

  # TODO/FIXME の書式チェック
  todo_format:
    name: "TODO Format"
    regex: "//\\s*(TODO|FIXME)(?!:)"
    message: "TODO/FIXME は 'TODO: 内容' の形式で書いてください"
    severity: warning

# レポーター（CI環境用）
reporter: "xcode"
