# SwiftLint Configuration for Tempo AI iOS

# 除外するルール
disabled_rules:
  - trailing_whitespace
  - function_body_length
  - type_body_length
  - trailing_comma
  - opening_brace  # Managed by swift-format; disabled to avoid conflicts

# 有効化するオプションルール  
opt_in_rules:
  - explicit_init
  - first_where
  - sorted_imports
  - vertical_parameter_alignment
  - closure_spacing
  - empty_count
  - file_name

file_name:
  excluded:
    - Models.swift
    - HomeViewComponents.swift

# 対象ディレクトリ
included:
  - TempoAI/TempoAI

# 除外ディレクトリ
excluded:
  - TempoAI/TempoAI/Assets.xcassets
  - TempoAI/TempoAI/Preview Content

# ルール設定
line_length: 120
identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - url
    - api
type_name:
  min_length: 3
  max_length: 40
function_parameter_count:
  warning: 5
  error: 8
cyclomatic_complexity:
  warning: 10
  error: 20
